name: Test:DruidDataSourceTest_exceptionSorter.test_event_error
run-name: Known Flaky test test_event_error
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl core test -Dtest=com.alibaba.druid.bvt.pool.DruidDataSourceTest_exceptionSorter#test_event_error
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.alibaba.druid.bvt.pool.DruidDataSourceTest_exceptionSorter#test_event_error
